; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; build_type = debug
; thomasfredericks/Bounce2@^2.70
; arkhipenko/TaskScheduler@^3.3.0
; monitor_filters = esp8266_exception_decoder, default
; links2004/WebSockets@^2.3.6
; esp32async/ESPAsyncTCP @ ^2.0.0
; https://github.com/dvarrel/ESPAsyncTCP.git
; esp32async/ESPAsyncWebServer @ ^3.8.0
; links2004/WebSockets @ ^2.7.0
; board_build.filesystem = littlefs

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -D ARDUINO_ARCH_ESP8266
lib_deps = 
    lennarthennigs/Button2 @ ^2.4.1
    links2004/WebSockets @ ^2.7.0
